dyscaling:
    name: DYscalingRDF
    path: Tools.Tools.dyreweighting
    parameters:
        year: self.config.year
        isDY: self.dataset.process.get_aux('isDY', False)

svfit:
    name: SVFitRDF
    path: Tools.Tools.svfit
    parameters:
        isMC: self.dataset.process.isMC

hh:
    name: HHKinFitRDF
    path: Tools.Tools.hh
    parameters:
        isMC: self.dataset.process.isMC

hhvar:
    name: HHVarRDF
    path: Tools.Tools.hh
    parameters:
        isMC: self.dataset.process.isMC

puweight:
    name: puWeightRDF
    path: Base.Modules.puWeightProducer
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year