svfit:
    name: SVFitRDFProducer
    path: Tools.Tools.svfit
    parameters:
        isMC: self.dataset.process.isMC

hh:
    name: HHKinFitRDFProducer
    path: Tools.Tools.hh
    parameters:
        isMC: self.dataset.process.isMC