2:
    name: MetFilterRDF
    path: Base.Modules.METfilters
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year


hhlepton:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        runPeriod: self.dataset.runPeriod
        filter: True


hhleptonVar:
    name: HHLeptonVarRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC


jet_smearing:
    name: jetSmearerRDF
    path: Base.Modules.smearing
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        jerTag: self.config.year


jet_smear_val:
    name: jetVarRDF
    path: Base.Modules.smearing
    parameters:
        isMC: self.dataset.process.isMC


met_smearing:
    name: metSmearerRDF
    path: Base.Modules.smearing
    parameters:
        isMC: self.dataset.process.isMC


# hhjets:
    # name: HHJetsRDF
    # path: Tools.Tools.HHJets
    # parameters:
        # year: self.config.year
        # isMC: self.dataset.process.isMC
        # met_smear_tag: smeared
        # filter: True


dyscaling:
    name: DYscalingRDF
    path: Tools.Tools.dyreweighting
    parameters:
        year: self.config.year
        isDY: self.dataset.process.get_aux('isDY', False)


svfit:
    name: SVFitRDF
    path: Tools.Tools.svfit
    parameters:
        isMC: self.dataset.process.isMC
        met_smear_tag: smeared


# # hh:
    # # name: HHKinFitRDF
    # # path: Tools.Tools.hh
    # # parameters:
        # # isMC: self.dataset.process.isMC
        # # met_smear_tag: smeared


# # hhvar:
    # # name: HHVarRDF
    # # path: Tools.Tools.hh
    # # parameters:
        # # isMC: self.dataset.process.isMC
        # # met_smear_tag: smeared


# trigSF:
    # name: Htt_trigSFRDF
    # path: Tools.Tools.Htt_trigSF
    # parameters:
        # year: self.config.year
        # isMC: self.dataset.process.isMC


# PUjetID_SF:
    # name: PUjetID_SFRDF
    # path: Tools.Tools.PUjetID_SF
    # parameters:
        # year: self.config.year
        # isMC: self.dataset.process.isMC


3_w2:
    name: prescaleWeightRDF
    path: Tools.Tools.weight
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year


4_w2:
    name: prefiringWeightRDF
    path: Base.Modules.prefiringWeight
    parameters:
        isMC: self.dataset.process.isMC


tauCorrections:
    name: tauSFRDF
    path: TauCorrections.TauCorrections.tauCorrections
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')
