# createJMECorrector:
    # path: PhysicsTools.NanoAODTools.postprocessing.modules.jme.jetmetHelperRun2
    # parameters:
        # isMC: self.dataset.isMC
        # dataYear: self.config.year
        # runPeriod: self.dataset.runPeriod
        # jesUncert: All
        # jetType: AK4PFchs
        # noGroom: False
        # splitJER: True

1:
    name: Counter
    path: cmt.modules.counter

2:
    name: HHLepton
    path: cmt.modules.HHLepton
    parameters:
        isMC: self.dataset.isMC
        year: self.config.year
        runPeriod: self.dataset.runPeriod

3:
    name: createJMECorrector
    path: PhysicsTools.NanoAODTools.postprocessing.modules.jme.jetmetHelperRun2
    parameters:
        isMC: self.dataset.isMC
        dataYear: self.config.year
        runPeriod: self.dataset.runPeriod
        jesUncert: Total
        jetType: AK4PFchs
        noGroom: False
        splitJER: True

4:
    name: HHJets
    path: cmt.modules.HHJets
    parameters:
        year: self.config.year
        isMC: self.dataset.isMC

5:
    name: SVFit
    path: cmt.modules.SVFit
    parameters:
        isMC: self.dataset.isMC

6:  
    name: HH
    path: cmt.modules.HH
    parameters:
        isMC: self.dataset.isMC