# createJMECorrector:
    # path: PhysicsTools.NanoAODTools.postprocessing.modules.jme.jetmetHelperRun2
    # parameters:
        # isMC: self.dataset.isMC
        # dataYear: self.config.year
        # runPeriod: self.dataset.runPeriod
        # jesUncert: All
        # jetType: AK4PFchs
        # noGroom: False
        # splitJER: True

# 1:
    # name: Counter
    # path: cmt.modules.counter

2:
    name: MetFilter
    path: cmt.modules.METfilters
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year

2_counter:
    name: Counter
    path: cmt.modules.counter
    parameters:
        histo_name: MetFilter

3_w1:
    name: puWeight
    path: cmt.modules.weight
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year

3_w2:
    name: prefiringWeight
    path: cmt.modules.weight
    parameters:
        isMC: self.dataset.process.isMC

tau_sf:
    name: tauCorrections
    path: cmt.modules.weight
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year

hhlep:
    name: HHLepton
    path: cmt.modules.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        runPeriod: self.dataset.runPeriod

hhlep_counter:
    name: Counter
    path: cmt.modules.counter
    parameters:
        histo_name: HHLepton

hhlep_var:
    name: HHLeptonVariable
    path: cmt.modules.HHLepton
    parameters:
        isMC: self.dataset.process.isMC

jet_syst:
    name: createJMECorrector
    path: PhysicsTools.NanoAODTools.postprocessing.modules.jme.jetmetHelperRun2
    parameters:
        isMC: self.dataset.process.isMC
        dataYear: self.config.year
        runPeriod: self.dataset.runPeriod
        jesUncert: Total
        jetType: AK4PFchs
        noGroom: False
        splitJER: True

hhjets:
    name: HHJets
    path: cmt.modules.HHJets
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC

hhjets_counter:
    name: Counter
    path: cmt.modules.counter
    parameters:
        histo_name: HHJets

trigSF:
    name: Htt_trigSF
    path: cmt.modules.Htt_trigSF
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC

svfit:
    name: SVFit
    path: cmt.modules.SVFit
    parameters:
        isMC: self.dataset.process.isMC

hh:  
    name: HH
    path: cmt.modules.HH
    parameters:
        isMC: self.dataset.process.isMC
