puweight:
    name: puWeightRDF
    path: Base.Modules.puWeightProducer
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year

dystitching:
    name: DYstitchingRDF
    path: Tools.Tools.dyreweighting
    parameters:
        year: self.config.year
        isDY: self.dataset.process.get_aux('isDY', False)